<!doctype html><html lang="en" data-default-theme="{{ auth()->user()->theme ?? 'light' }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Dashboard') - Eemo Find</title>@vite(['resources/css/app.css','resources/js/app.js'])@stack('head')</head>
<body><div class="app-shell"><aside class="sidebar"><a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark"><i class="bi bi-geo-alt-fill"></i></span><span>Eemo Find</span></a><div class="nav-label">Overview</div><nav class="nav flex-column"><a class="nav-link {{ request()->routeIs('dashboard')?'active':'' }}" href="{{ route('dashboard') }}"><i class="bi bi-grid"></i>Dashboard</a>
@can('users.view')<a class="nav-link" href="{{ route('admin.resources.index','users') }}"><i class="bi bi-people"></i>Users</a>@endcan
@can('devices.view')<a class="nav-link" href="{{ route('admin.resources.index','devices') }}"><i class="bi bi-router"></i>Devices</a>@endcan
@can('groups.view')<a class="nav-link" href="{{ route('admin.resources.index','groups') }}"><i class="bi bi-diagram-3"></i>Groups</a>@endcan
<div class="nav-label">Commerce</div>@can('plans.view')<a class="nav-link" href="{{ route('admin.resources.index','plans') }}"><i class="bi bi-box-seam"></i>Plans</a>@endcan
@can('reports.view')<a class="nav-link" href="{{ route('admin.reports.index') }}"><i class="bi bi-graph-up"></i>Payments & Reports</a>@endcan
<div class="nav-label">Operations</div>@can('tickets.view')<a class="nav-link" href="{{ route('admin.tickets.index') }}"><i class="bi bi-life-preserver"></i>Support Tickets</a>@endcan
@can('faqs.view')<a class="nav-link" href="{{ route('admin.resources.index','faqs') }}"><i class="bi bi-question-circle"></i>FAQs</a>@endcan
@can('geofences.view')<a class="nav-link" href="{{ route('admin.resources.index','geofences') }}"><i class="bi bi-bounding-box-circles"></i>Geofences</a>@endcan
@can('settings.view')<a class="nav-link" href="{{ route('admin.settings.edit') }}"><i class="bi bi-gear"></i>Settings</a>@endcan</nav></aside>
<main class="main"><header class="topbar"><button class="btn btn-link text-body d-lg-none" data-sidebar-toggle><i class="bi bi-list fs-4"></i></button><div class="input-group ms-2" style="max-width:420px"><span class="input-group-text border-0 bg-transparent"><i class="bi bi-search"></i></span><input class="form-control border-0 shadow-none" placeholder="Search users, devices, tickets..."></div><div class="ms-auto d-flex align-items-center gap-2"><button class="btn btn-light rounded-circle" data-theme-toggle title="Switch theme"><i class="bi bi-circle-half"></i></button><div class="dropdown"><button class="btn btn-light rounded-circle position-relative" data-bs-toggle="dropdown"><i class="bi bi-bell"></i>@if(auth()->user()->unreadNotifications()->count())<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">{{ min(9,auth()->user()->unreadNotifications()->count()) }}</span>@endif</button><div class="dropdown-menu dropdown-menu-end p-2" style="width:320px">@forelse(auth()->user()->notifications()->latest()->limit(5)->get() as $note)<div class="p-2 border-bottom"><div class="fw-semibold">{{ $note->data['title']??'Notification' }}</div><small class="text-muted">{{ $note->data['message']??'' }}</small></div>@empty<div class="empty-state py-4">No notifications</div>@endforelse</div></div><div class="dropdown"><button class="btn d-flex align-items-center gap-2" data-bs-toggle="dropdown"><span class="avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><span class="d-none d-md-block text-start"><b>{{ auth()->user()->name }}</b><small class="d-block text-muted">{{ auth()->user()->roles->first()?->name ?? 'User' }}</small></span></button><div class="dropdown-menu dropdown-menu-end"><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#passwordModal"><i class="bi bi-key me-2"></i>Change password</button><form method="POST" action="{{ route('logout') }}">@csrf<button class="dropdown-item text-danger"><i class="bi bi-box-arrow-right me-2"></i>Logout</button></form></div></div></div></header><section class="content">@if($errors->any())<div class="alert alert-danger"><b>Please fix the following:</b><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</section></main></div>
<div class="modal fade" id="passwordModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('password.change') }}">@csrf<div class="modal-header"><h5 class="modal-title">Change password</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Current password</label><input type="password" name="current_password" class="form-control mb-3" required><label class="form-label">New password</label><input type="password" name="password" class="form-control mb-3" required><label class="form-label">Confirm password</label><input type="password" name="password_confirmation" class="form-control" required></div><div class="modal-footer"><button class="btn btn-primary">Update password</button></div></form></div></div>
<script>window.flashSuccess=@json(session('success'));window.flashError=@json(session('error'));</script>@stack('scripts')</body></html>
